### ISSUE TITLE
@vitjs/runtime 导出的History，是否应该为history

### ISSUE THREAD

**Issue by 18583952605** [vitjs/vit#5]
实际导出的是history，类型里写的是History

![image](https://user-images.githubusercontent.com/22405993/173178204-4de4033d-500e-429d-93e8-0217f7d86793.png)

**Comment by yunsii** [comment]
导出的是这个 react-router 的 history，在这里：https://github.com/vitjs/vit/blob/master/packages/vit/src/generateFiles/exports.tpl#L3

**Comment by 18583952605** [comment]
![image](https://user-images.githubusercontent.com/22405993/173387363-4498528e-00a8-4307-b6b9-d0cc137e96a5.png)
这个文件里没有写导出 history，页面导入 history 的时候，编辑器有个警告提示。。

**Comment by 18583952605** [comment]
好像是我编辑器的问题。。。可以关闭issues啦
