### ISSUE TITLE
不支持hash模式吗

### ISSUE THREAD

**Issue by 18583952605** [vitjs/vit#6]
![image](https://user-images.githubusercontent.com/22405993/174478152-6fdeb534-f199-4dd0-9405-aaca9fb81c24.png)

这样写的，没生效，

还是 http://localhost:8000/vite-react/ant-design 这种路径

**Comment by yunsii** [comment]
可以看一下生成的代码，example 下的代码测试 hash 路由是没问题的
![image](https://user-images.githubusercontent.com/18096089/174480799-85696fdc-05e8-439f-bf10-ada0c39ff3b2.png)

**Comment by yunsii** [comment]
也有可能是缓存问题，可尝试清楚 Vite 缓存后重试。

Close as stale.
