### ISSUE TITLE
Having an issue with a basic react app

### ISSUE THREAD

**Issue by alkanna** [vitjs/vit#7]
Hello, I tried to reproduce the example at yunsii/vite-react

I end up with these errors and a blank page 😢 

![CleanShot 2022-07-08 at 22 55 28](https://user-images.githubusercontent.com/30343764/178069136-787b2231-958a-4ad8-acb0-29a49c4a3d2c.png)

My _app.tsx, vite.config.ts and routes.ts are the exact same as shown in yunsii/vite-react

**Comment by yunsii** [comment]
Thanks for your feedback. Please tell me which branch you use in yunsii/vite-react, and  the versions of react and vitjs has changed?

**Comment by yunsii** [comment]
Moreover, consider provide a reproduce repo?

**Comment by yunsii** [comment]
The error casued by `use-subscription` the same major version of `^1.5.1`, I fixed it by `~1.5.1` in https://github.com/vitjs/vit/pull/9 so upgrade `vitjs/vit` & `vitjs/runtime` to lastest version will fix the error.
